# Built with Jekyll 3.2.0

# Setup
title:               "Just Passing Time"
tagline:             'The Collected Poems of Arnold Marks'
description:         'These pages are dedicated to the written works of my grandfather, Arnold Marks.'
url:                 'https://catchcase.github.io'
baseurl:             '/arnold-marks'

# About/contact
author:
  name:              Vincente Campisi
  url:               https://github.com/catchcase
  email:             catchcaseio@gmail.com

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
